const enum Subject {
  MATH = 'MATH',
  ENGLISH = 'ENGLISH',
  SCIENCE = 'SCIENCE',
  HISTORY = 'HISTORY',
  GEOGRAPHY = 'GEOGRAPHY',
  COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
  PHYSICS = 'PHYSICS',
  CHEMISTRY = 'CHEMISTRY',
  BIOLOGY = 'BIOLOGY',
  ECONOMICS = 'ECONOMICS',
  CIVICS = 'CIVICS',
  GOVERNMENT = 'GOVERNMENT',
  LITERATURE = 'LITERATURE',
  ART = 'ART',
  MUSIC = 'MUSIC',
  SPORT = 'SPORT',
  HEALTH = 'HEALTH',
  SPANISH = 'SPANISH',
  FRENCH = 'FRENCH',
  GERMAN = 'GERMAN',
}

export default Subject;
