-- CreateEnum
CREATE TYPE "Type" AS ENUM ('MULTIPLE_CHOICE', 'SINGLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER');

-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "type" "Type" NOT NULL DEFAULT 'MULTIPLE_CHOICE';
