export const randomNames = [
  'Kaeli Killen',
  'Lyam Sturgeon',
  'Hadley Tarango',
  'Leighton Judd',
  'Bodie Barney',
  'Jacquelyn Escamilla',
  'Maegan Zabala',
  'Geraldine Gossett',
  'Abree Whitmer',
  'Ameera Hiatt',
  'Zayde Gust',
  'Minha Bogue',
  'Mahayla Dieter',
  'Amador Balogh',
  'Zaelynn Shabazz',
  'Jeriah Roundtree',
  'Abigale Burge',
  'Aariah Delay',
  'Kaili Borja',
  'Zac Chavira',
  'Kaelynn Cody',
  'Jolee Maas',
  'Teagan Power',
  'Hagan Fricke',
  'Haven Tanner',
  'Carrick Hetherington',
  'Fionn Welling',
  'Austyn Hidalgo',
  'Duke Burks',
  'Gabby Deming',
];

export function getRandomName() {
  return randomNames[Math.floor(Math.random() * randomNames.length)];
}
